export const SET_USER_MATCHES = 'CHAT/SET_USER_MATCHES';
export const SET_IS_OPEN_CHAT_ROOM = 'CHAT/SET_IS_OPEN_CHAT_ROOM';
export const SET_CHAT_TOKEN = 'CHAT/SET_CHAT_TOKEN';
export const SET_FIRST_PACK_MESSAGES = 'CHAT/SET_FIRST_PACK_MESSAGES';










