export const SET_USER_MATCHES = 'CHAT/SET_USER_MATCHES';
export const SET_IS_OPEN_CHAT_ROOM = 'CHAT/SET_IS_OPEN_CHAT_ROOM';
export const SET_CHAT_TOKEN = 'CHAT/SET_CHAT_TOKEN';
export const SET_FIRST_PACK_MESSAGES = 'CHAT/SET_FIRST_PACK_MESSAGES';
export const SET_USER_IN_CHAT = 'CHAT/SET_USER_IN_CHAT';
export const SET_NOTIFICATION_ABOUT_NEW_MESSAGES = 'CHAT/SET_NOTIFICATION_ABOUT_NEW_MESSAGES';
export const CLOSE_NOTIFICATION_ABOUT_NEW_MESSAGES = 'CHAT/CLOSE_NOTIFICATION_ABOUT_NEW_MESSAGES';
export const SET_NOTIFICATION_ABOUT_NEW_VISIT = 'CHAT/SET_NOTIFICATION_ABOUT_NEW_VISIT';











