export const SET_USER_MATCHES = 'CHAT/SET_USER_MATCHES';
export const SET_USER_MESSAGES = 'CHAT/SET_USER_MESSAGES';
export const SET_USER_LIKES = 'CHAT/SET_USER_LIKES';
export const SET_USER_VISITS = 'CHAT/SET_USER_VISITS';
export const SET_IS_OPEN_CHAT_ROOM = 'CHAT/SET_IS_OPEN_CHAT_ROOM';
export const SET_CHAT_TOKEN = 'CHAT/SET_CHAT_TOKEN';
export const SET_FIRST_PACK_MESSAGES = 'CHAT/SET_FIRST_PACK_MESSAGES';
export const SET_USER_IN_CHAT = 'CHAT/SET_USER_IN_CHAT';
export const SET_NOTIFICATION_ABOUT_NEW_MESSAGES = 'CHAT/SET_NOTIFICATION_ABOUT_NEW_MESSAGES';
export const CLOSE_NOTIFICATION_ABOUT_NEW_MESSAGES = 'CHAT/CLOSE_NOTIFICATION_ABOUT_NEW_MESSAGES';
export const SET_NOTIFICATION_ABOUT_NEW_VISIT = 'CHAT/SET_NOTIFICATION_ABOUT_NEW_VISIT';
export const SET_RECEVIED_CHAT_NOTICE = 'CHAT/SET_RECEVIED_CHAT_NOTICE';
export const SET_CURRENT_USER_MESSAGES = 'CHAT/SET_CURRENT_USER_MESSAGES';
export const SET_USER_FI_IN_LAST_NOTIFICATION = 'CHAT/SET_USER_FI_IN_LAST_NOTIFICATION';
export const SET_IS_SHOW_FALSE_FOR_NOTIFICATION = 'CHAT/SET_IS_SHOW_FALSE_FOR_NOTIFICATION';
export const CLOSE_OPEN_CHAT_ROOM = 'MAIN_PAGE/CLOSE_OPEN_CHAT_ROOM';
export const CLEAR_CHAT_PAGE = 'MAIN_PAGE/CLEAR_CHAT_PAGE';










