export const SET_USER_ACCOUNT = 'MAIN_PAGE/SET_USER_ACCOUNT';
export const SET_USER_ORIENT = 'MAIN_PAGE/SET_USER_ORIENT';
export const SET_USER_EDUCATION = 'MAIN_PAGE/SET_USER_EDUCATION';
export const SET_USER_WORK_PLACE = 'MAIN_PAGE/SET_USER_WORK_PLACE';
export const SET_USER_POSITION = 'MAIN_PAGE/SET_USER_POSITION';
export const SET_USER_BIOGRAPHY = 'MAIN_PAGE/SET_USER_BIOGRAPHY';
export const SET_USER_TAGS = 'MAIN_PAGE/SET_USER_TAGS';
export const DELETE_USER_TAGS = 'MAIN_PAGE/DELETE_USER_TAGS';






